name: close inactive issues
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v4
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 14
          stale-issue-label: 'stale'
          stale-issue-message: 'hey 👋 - silence for 30 days 🤐 ... anybody? 😀'
          close-issue-message: 'closed 📴 because silencio 🤫 since an additional 14 days after staleness 📠'
          exempt-issue-labels: 'enhancement,feature request'
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
